# Config
CONFIG_FILE_NOT_FOUND = 1
NO_VALID_COOKIE_DETECTED = 2
# Parser
CANT_PARSE_FAV_CATEGORY = 3
CANT_PARSE_FAV_LIST = 4
CANT_PARSE_GALLERY = 5
CANT_PARSE_IMG_PAGE = 6
CANT_FETCH_EHAPI = 7
BUMPED_509 = 8
