"""Modify some column

Revision ID: 5e0ec12748d6
Revises: f06f1b8d9237
Create Date: 2023-06-07 03:13:01.025971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0ec12748d6'
down_revision = 'f06f1b8d9237'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doujinshi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.TEXT(), nullable=True))
        batch_op.drop_column('first_gid')
        batch_op.drop_column('current_key')
        batch_op.drop_column('parent_key')
        batch_op.drop_column('first_key')
        batch_op.drop_column('current_gid')
        batch_op.drop_column('parent_gid')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doujinshi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_gid', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('current_gid', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('first_key', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('parent_key', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('current_key', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('first_gid', sa.INTEGER(), nullable=True))
        batch_op.drop_column('tag')
        batch_op.drop_column('language')
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
