"""refactor: add some column

Revision ID: f06f1b8d9237
Revises: 
Create Date: 2023-04-16 13:52:39.541367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06f1b8d9237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doujinshi', 'finished', new_column_name='status')
    op.add_column('doujinshi', sa.Column('artist', sa.TEXT(), nullable=True))
    op.add_column('doujinshi', sa.Column('parent_gid', sa.INTEGER(), nullable=True))
    op.add_column('doujinshi', sa.Column('parent_key', sa.TEXT(), nullable=True))
    op.add_column('doujinshi', sa.Column('first_gid', sa.INTEGER(), nullable=True))
    op.add_column('doujinshi', sa.Column('first_key', sa.TEXT(), nullable=True))
    op.add_column('doujinshi', sa.Column('current_gid', sa.INTEGER(), nullable=True))
    op.add_column('doujinshi', sa.Column('current_key', sa.TEXT(), nullable=True))
    op.add_column('doujinshi', sa.Column('favorited_time', sa.DATE(), nullable=True))
    op.add_column('img', sa.Column('md5', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('img', 'md5')
    op.alter_column('doujinshi', 'status', new_column_name='finished')
    op.drop_column('doujinshi', 'favorited_time')
    op.drop_column('doujinshi', 'current_key')
    op.drop_column('doujinshi', 'current_gid')
    op.drop_column('doujinshi', 'first_key')
    op.drop_column('doujinshi', 'first_gid')
    op.drop_column('doujinshi', 'parent_key')
    op.drop_column('doujinshi', 'parent_gid')
    op.drop_column('doujinshi', 'artist')
    # ### end Alembic commands ###
